baseURL = "https://miskaryan.net/"
languageCode = "en-us"
title = "Alexander Miskaryan"
theme = "smol"

# Parameters
[params]
    subtitle = "Yet another nerd cave"
    dateFmt = "02.01.2006"

# Header
[menu]
  [[menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts/"
        weight = 1

  [[menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags/"
        weight = 2

# Footer
  [[menu.footer]]
        name = "Github"
        url = "https://github.com/alexmisk"
        weight = 1

